name: gen
description: "A new Flutter project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  envied: ^0.5.4+1
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0

flutter_gen:
  outputs:
    package_parameter_enabled: true
  output: lib/src/asset/
  integration:
    lottie: true
    flutter_svg: true

flutter:
  assets:
    - assets/icon/
    - assets/lottie/
    - assets/image/
