name: bike_city
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # network manager
  vexana: ^5.0.1

  # utility
  kartal: ^4.1.0

  # core dependicies
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  envied: ^0.5.4+1


  # icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  very_good_analysis: ^6.0.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/icon.png"
  remove_alpha_ios: true


flutter_gen:
  outputs: lib/product/generated/
  integration:
    lottie: true

flutter:


  uses-material-design: true

