name: bike_city
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # network
  vexana: ^5.0.1

  # utility
  kartal: ^4.1.0
  easy_logger: ^0.0.2
  logger: ^2.4.0

  # core dependicies
  equatable: ^2.0.5

  # localization
  easy_localization: ^3.0.7

  # navigation
  auto_route: ^7.8.4


  # icons
  cupertino_icons: ^1.0.8


  widgets:
    path: module/widgets

  gen:
    path: module/gen

  common:
    path: module/common

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  auto_route_generator: ^7.3.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/icon.png"
  remove_alpha_ios: true


flutter:

  assets:
    - assets/translations/
    - assets/env/



  uses-material-design: true

